title: Byng Road Allotments
description: The Byng Road Allotments Group (BRAG) provides allotments for the residents of the London Borough of Barnet in the UK.
logo: /assets/images/site-logo.png

markdown: kramdown
permalink: pretty

# GitHub Pages-compatible default behavior
safe: true
lsi: false

defaults:
  - scope:
      path: ""
    values:
      layout: default

include:
  - _layouts
  - _pages